name: Optimize map and deploy

on: [push]

permissions:
  contents: write
  pages: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install

      - name: "Build scripts"
        run: npm run build

      - name: Get API KEY from secrets
        env:
          MAP_STORAGE_API_KEY: ${{ secrets.MAP_STORAGE_API_KEY }}
        run: echo "MAP_STORAGE_API_KEY=${MAP_STORAGE_API_KEY}" >> $GITHUB_ENV

      - name: Get MAP STORAGE URL from secrets
        env:
          MAP_STORAGE_URL: ${{ secrets.MAP_STORAGE_URL }}
        run: echo "MAP_STORAGE_URL=${MAP_STORAGE_URL}" >> $GITHUB_ENV

      - name: Generate .env.secret
        run: echo "MAP_STORAGE_API_KEY=${{ secrets.MAP_STORAGE_API_KEY }}" > .env.secret

      - name: Extract UPLOAD_MODE from .env
        run: echo "UPLOAD_MODE=$(grep '^[^#]*UPLOAD_MODE' .env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Extract UPLOAD DIRECTORY from Github
        run: echo "UPLOAD_DIRECTORY=${{ github.actor }}-${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Create or update .env file
        run: |
          UPLOAD_DIRECTORY="${{ github.actor }}-${{ github.event.repository.name }}"
          echo "UPLOAD_DIRECTORY=${UPLOAD_DIRECTORY}" > .env

      - name: Deploy in MAP STORAGE
        if: ${{ env.UPLOAD_MODE == 'MAP_STORAGE' }}
        run: npm run upload-only

      - name: Deploy on GITHUB PAGES
        if: ${{ env.UPLOAD_MODE == 'GH_PAGES' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/
          BASE_BRANCH: master
